safe: true
lsi: false
pygments: true
excerpt_separator: "[end_excerpt]"
markdown:  rdiscount
paginate: 10
paginate_path: "/blog/page:num"
tag_page_dir: tag
tag_page_layout: tag_page
permalink: /:year/:month/:day/:title/
navigation:
- text: Downloads
  url: http://app.ironfoundry.me/download
- text: Sign Up
  url: http://app.ironfoundry.me/signup
- text: Blog
  url: /blog/index.html
- text: Help
  url: /help.html
- text: About
  url: /about.html