lsi: false
exclude: [less]
pygments: true
markdown_ext:  markdown,mkd,mkdn,md
markdown:  rdiscount
paginate: 10
paginate_path: "/blog/page:num"
tag_page_layout: tag_page
tag_page_dir: tag
permalink: /:year/:month/:day/:title/
navigation:
- text: Downloads
  url: http://app.ironfoundry.me/download
- text: Sign Up
  url: http://app.ironfoundry.me/signup
- text: Blog
  url: /blog
- text: Help
  url: /help
- text: About
  url: /about